version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Newtonsoft.Json
    versions:
    - ">= 10.a, < 11"
  - dependency-name: Newtonsoft.Json
    versions:
    - ">= 11.a, < 12"
  - dependency-name: Newtonsoft.Json
    versions:
    - ">= 12.a, < 13"
  - dependency-name: Newtonsoft.Json
    versions:
    - ">= 13.a, < 14"
  - dependency-name: NuGet.VisualStudio
    versions:
    - "> 3.3.0, < 4"
  - dependency-name: NuGet.VisualStudio
    versions:
    - ">= 4.a, < 5"
  - dependency-name: NuGet.VisualStudio
    versions:
    - ">= 5.a, < 6"
