language: csharp
mono: none
dotnet: 2.1
script:
  - dotnet restore src/CLI/ApiClientCodeGen.CLI/ApiClientCodeGen.CLI.csproj
  - dotnet build src/CLI/ApiClientCodeGen.CLI/ApiClientCodeGen.CLI.csproj
  - dotnet pack src/CLI/ApiClientCodeGen.CLI/ApiClientCodeGen.CLI.csproj