name: CLI Tool

on: [push, pull_request]
  schedule:
    - cron:  '0 8 * * *'

jobs:
  build:
  
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.607

    - name: Build with dotnet
      run: dotnet build Rapicgen.sln
      working-directory: src

    - name: Test with dotnet
      run: dotnet test Rapicgen.sln
      working-directory: src
