name: CLI Tool

on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'test/**'
      - 'build/**'
      - 'images/**'
      - 'README.md'
      - 'src/VSIX/ApiClientCodeGen.VSIX*/**'
      - 'src/VSIX/ApiClientCodeGen.Tests/**'
      - 'src/VSMac/ApiClientCodeGen.VSMac*/**'
      - 'src/VSIX/ApiClientCodeGen.IntegrationTests/**'
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron:  '0 8 * * *'

jobs:
  build:
  
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.607

    - name: Build with dotnet
      run: dotnet build Rapicgen.sln
      working-directory: src

    - name: Core test project
      run: dotnet test src/Core/ApiClientCodeGen.Core.Tests/ApiClientCodeGen.Core.Tests.csproj
      continue-on-error: true

    - name: Build .NET Tool package
      run: dotnet pack src/CLI/ApiClientCodeGen.CLI/ApiClientCodeGen.CLI.csproj
