name: CLI Tool

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/workflows/**'
      - '!.github/workflows/cli-tool.yml'
      - 'docs/**'
      - 'test/**'
      - 'build/**'
      - 'images/**'
      - 'README.md'
      - 'src/VSIX/ApiClientCodeGen.VSIX*/**'
      - 'src/VSIX/ApiClientCodeGen.Tests/**'
      - 'src/VSMac/ApiClientCodeGen.VSMac*/**'
      - 'src/VSIX/ApiClientCodeGen.IntegrationTests/**'
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron:  '0 8 * * *'

env:
  VERSION: 1.4.${{ github.run_number }}

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Sets environment variables - branch-name
      uses: nelonoel/branch-name@v1.0.1
    - name: Sets environment variables - Nerdbank.GitVersioning
      uses: dotnet/nbgv@master

    - name: Build with dotnet
      run: dotnet build Rapicgen.sln
      working-directory: src

    - name: Core test project
      run: dotnet test src/Core/ApiClientCodeGen.Core.Tests/ApiClientCodeGen.Core.Tests.csproj
      continue-on-error: true
    
    - name: Build
      run: dotnet build -c Release /p:UseSourceLink=true src/Rapicgen.sln -p:PackageVersion="${{ env.VERSION }}"

    - name: Package
      run: dotnet pack --no-build -c Release /p:UseSourceLink=true src/CLI/ApiClientCodeGen.CLI/ApiClientCodeGen.CLI.csproj -p:PackageVersion="${{ env.VERSION }}"

    - name: Publish artifacts
      uses: actions/upload-artifact@v2
      with:
        name: CLI Tool
        path: |
          **/*.nupkg
          docs/CLI.md
