name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - 'release'

env:
  VERSION: 1.4.${{ github.run_number }}
  NUGET_REPO_URL: 'https://api.nuget.org/v3/index.json'

jobs:

  VSIX:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Sets environment variables - branch-name
      uses: nelonoel/branch-name@v1.0.1
    - name: Sets environment variables - Nerdbank.GitVersioning
      uses: dotnet/nbgv@master
      with:
        setAllVars: true
    - name: Update Version
      run: |
        ((Get-Content -Path Core/ApiClientCodeGen.Core/ApiClientCodeGen.Core.csproj -Raw) -Replace "1.0.0", "${{ env.VERSION }}") | Set-Content -Path Core/ApiClientCodeGen.Core/ApiClientCodeGen.Core.csproj
        ((Get-Content -Path VSIX/ApiClientCodeGen.VSIX/source.extension.vsixmanifest -Raw) -Replace "1.0.0", "${{ env.VERSION }}") | Set-Content -Path VSIX/ApiClientCodeGen.VSIX/source.extension.vsixmanifest
        ((Get-Content -Path VSIX/ApiClientCodeGen.VSIX.Dev17/source.extension.vsixmanifest -Raw) -Replace "1.0.0", "${{ env.VERSION }}") | Set-Content -Path VSIX/ApiClientCodeGen.VSIX.Dev17/source.extension.vsixmanifest
      working-directory: src
      shell: pwsh
    - name: Cake Build
      run: powershell ./build.ps1 --target VSIX
      working-directory: src
    - name: Move build output
      run: |
        mv src/VSIX/ApiClientCodeGen.VSIX/bin/Release/ApiClientCodeGenerator.vsix ApiClientCodeGenerator-${{ env.VERSION }}.vsix
        mv src/VSIX/ApiClientCodeGen.VSIX.Dev17/bin/Release/ApiClientCodeGenerator.vsix ApiClientCodeGenerator-VS2022-${{ env.VERSION }}.vsix
    - name: Publish artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Visual Studio Extension
        path: |
          *.vsix
          docs/Marketplace*.md
    - name: Publish VSIX Packages
      run: |
        $VsixPublisher = "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VSSDK\VisualStudioIntegration\Tools\Bin\VsixPublisher.exe"
        & $VsixPublisher login -personalAccessToken ${{ secrets.MARKETPLACE_PAT }} -publisherName ChristianResmaHelle
        & $VsixPublisher publish -payload ApiClientCodeGenerator-${{ env.VERSION }}.vsix -publishManifest src/publish-manifest.json -ignoreWarnings 'VSIXValidatorWarning01,VSIXValidatorWarning02'
        & $VsixPublisher publish -payload ApiClientCodeGenerator-VS2022-${{ env.VERSION }}.vsix -publishManifest src/publish-manifest-vs2022.json -ignoreWarnings 'VSIXValidatorWarning01,VSIXValidatorWarning02'

  CLI:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Sets environment variables - branch-name
      uses: nelonoel/branch-name@v1.0.1
    - name: Sets environment variables - Nerdbank.GitVersioning
      uses: dotnet/nbgv@master
      with:
        setAllVars: true
    - name: Build
      run: dotnet build -c Release /p:UseSourceLink=true src/Rapicgen.sln -p:PackageVersion="${{ env.VERSION }}"
    - name: Package
      run: dotnet pack -c Release /p:UseSourceLink=true src/CLI/ApiClientCodeGen.CLI/ApiClientCodeGen.CLI.csproj -p:PackageVersion="${{ env.VERSION }}"
    - name: Push packages to NuGet
      run: dotnet nuget push **/*.nupkg -k ${{ secrets.NUGET_KEY }} -s ${{ env.NUGET_REPO_URL }} --no-symbols true
    - name: Publish artifacts
      uses: actions/upload-artifact@v2
      with:
        name: CLI Tool
        path: |
          **/*.nupkg
          docs/CLI.md
  
  VSMac:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - name: Sets environment variables - branch-name
      uses: nelonoel/branch-name@v1.0.1
    - name: Sets environment variables - Nerdbank.GitVersioning
      uses: dotnet/nbgv@master
      with:
        setAllVars: true
    - name: Update Extension Version Info
      run: |
        sed -i -e 's/1.0/${{ env.VERSION }}/g' ./AddinInfo.cs
        cat ./AddinInfo.cs
      working-directory: src/VSMac/ApiClientCodeGen.VSMac/Properties
    - name: Build
      run: make release
      working-directory: src
    - name: Archive binaries
      run: zip -r VSMac-Binaries.zip .
      working-directory: src/VSMac/ApiClientCodeGen.VSMac/bin/Release/net472/
    - name: Create mpack file
      run: make package
      working-directory: src
    - name: Rename build output
      run: mv *.mpack ApiClientCodeGenerator-${{ env.VERSION }}.mpack
      working-directory: src
    - name: Create MonoDevelop Extension repository files
      run: make publish
      working-directory: src
    - name: Update .mrep files
      run: |
        [xml]$latestRoot = Get-Content root.mrep
        $resultRoot = '<?xml version="1.0" encoding="utf-8"?>'
        $resultRoot += '<Repository xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">'
        $resultRoot += (Invoke-RestMethod 'https://christianhelle.com/vsmac/root.mrep').Repository.InnerXml + $latestRoot.Repository.InnerXml
        $resultRoot += '</Repository>'
        ([xml]$resultRoot).Save("$pwd\root.mrep")

        $main = '<?xml version="1.0" encoding="utf-8"?>'
        $main += '<Repository xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">'
        $main += '<Repository>'
        $main += '<Url>root.mrep</Url>'
        $main += '<LastModified>'
        $main += (Get-Date).ToString('o')
        $main += '</LastModified>'
        $main += '</Repository>'
        $main += '</Repository>'
        ([xml]$main).Save("$pwd\main.mrep")
      working-directory: src
      shell: pwsh
    - name: Publish artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Visual Studio for Mac Extension
        path: |
          src/VSMac/ApiClientCodeGen.VSMac/bin/Release/net472/VSMac-Binaries.zip
          src/*.mpack
          src/*.mrep
          src/index.html
          docs/VisualStudioForMac.md
    - name: Upload files to FTP
      working-directory: src
      shell: pwsh
      run: |
        $local_files = @("ApiClientCodeGenerator-${{ env.VERSION }}.mpack", "main.mrep", "root.mrep", "index.html")
        $remote_path = "${{ secrets.FTP_HOSTNAME }}/public_html/vsmac/"
                
        ForEach ($local_file in $local_files) {
          $ftprequest = [System.Net.FtpWebRequest]::Create("$remote_path/$local_file")
          $ftprequest = [System.Net.FtpWebRequest]$ftprequest
          $ftprequest.Method = [System.Net.WebRequestMethods+Ftp]::UploadFile
          $ftprequest.Credentials = new-object System.Net.NetworkCredential("${{ secrets.FTP_USERNAME }}", "${{ secrets.FTP_PASSWORD }}")
          $ftprequest.UseBinary = $true
          $ftprequest.UsePassive = $true
          $filecontent = [System.IO.File]::ReadAllBytes((Get-ChildItem $local_file).FullName)
          $ftprequest.ContentLength = $filecontent.Length
          $run = $ftprequest.GetRequestStream()
          $run.Write($filecontent, 0, $filecontent.Length)
          $run.Dispose()
        }

  Tag:
    needs: [VSIX, CLI, VSMac]
    runs-on: ubuntu-latest
    steps:
    - name: Create tag
      uses: actions/github-script@v3
      with:
        github-token: ${{ github.token }}
        script: |
          github.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: "refs/tags/${{ env.VERSION }}",
            sha: context.sha
          })
