name: Smoke Tests

on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'build/**'
      - 'images/**'
      - 'README.md'
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron:  '0 8 * * *'

jobs:

  test-petstore-v2-json:

    name: Swagger Petstore v2 (JSON)
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core 2.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1
    
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1
    
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0

    - name: Download Swagger Petstore v2 OpenAPI Spec
      run: Invoke-WebRequest -Uri https://petstore.swagger.io/v2/swagger.json -OutFile OpenApi.json
      working-directory: test

    - name: Generate code with AutoRest
      run: dotnet run --project ../src/ApiClientCodeGen.CLI/ApiClientCodeGen.CLI.csproj -- -v autorest ./OpenApi.json GeneratedCode ./GeneratedCode/AutoRest/Output.cs
      working-directory: test

    - name: Build .NET Core 2.1 AutoRest generated code
      run: dotnet build ./GeneratedCode/AutoRest/NetCore21.csproj
      working-directory: test

    - name: Build .NET Core 3.1 AutoRest generated code
      run: dotnet build ./GeneratedCode/AutoRest/NetCore31.csproj
      working-directory: test

    - name: Build .NET 5 AutoRest generated code
      run: dotnet build ./GeneratedCode/AutoRest/Net5.csproj
      working-directory: test

    - name: Generate code with NSwag
      run: dotnet run --project ../src/ApiClientCodeGen.CLI/ApiClientCodeGen.CLI.csproj -- -v nswag ./OpenApi.json GeneratedCode ./GeneratedCode/NSwag/Output.cs
      working-directory: test

    - name: Build .NET Core 2.1 NSwag generated code
      run: dotnet build ./GeneratedCode/NSwag/NetCore21.csproj
      working-directory: test

    - name: Build .NET Core 3.1 NSwag generated code
      run: dotnet build ./GeneratedCode/NSwag/NetCore31.csproj
      working-directory: test

    - name: Build .NET 5 NSwag generated code
      run: dotnet build ./GeneratedCode/NSwag/Net5.csproj
      working-directory: test

    - name: Generate code with Swagger Codegen CLI
      run: dotnet run --project ../src/ApiClientCodeGen.CLI/ApiClientCodeGen.CLI.csproj -- -v nswag ./OpenApi.json GeneratedCode ./GeneratedCode/SwaggerCodegen/Output.cs
      working-directory: test

    - name: Build .NET Core 2.1 Swagger Codegen CLI generated code
      run: dotnet build ./GeneratedCode/SwaggerCodegen/NetCore21.csproj
      working-directory: test

    - name: Build .NET Core 3.1 Swagger Codegen CLI generated code
      run: dotnet build ./GeneratedCode/SwaggerCodegen/NetCore31.csproj
      working-directory: test

    - name: Build .NET 5 Swagger Codegen CLI generated code
      run: dotnet build ./GeneratedCode/SwaggerCodegen/Net5.csproj
      working-directory: test

    - name: Generate code with OpenAPI Generator
      run: dotnet run --project ../src/ApiClientCodeGen.CLI/ApiClientCodeGen.CLI.csproj -- -v nswag ./OpenApi.json GeneratedCode ./GeneratedCode/OpenApiGenerator/Output.cs
      working-directory: test

    - name: Build .NET Core 2.1 OpenAPI Generator generated code
      run: dotnet build ./GeneratedCode/OpenApiGenerator/NetCore21.csproj
      working-directory: test

    - name: Build .NET Core 3.1 OpenAPI Generator generated code
      run: dotnet build ./GeneratedCode/OpenApiGenerator/NetCore31.csproj
      working-directory: test

    - name: Build .NET 5 OpenAPI Generator generated code
      run: dotnet build ./GeneratedCode/OpenApiGenerator/Net5.csproj
      working-directory: test

  test-petstore-v2-yaml:

    name: Swagger Petstore v2 (YAML)
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core 2.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1
    
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1

    - name: Download Swagger Petstore v2 OpenAPI Spec
      run: Invoke-WebRequest -Uri https://petstore.swagger.io/v2/swagger.yaml -OutFile OpenApi.yaml
      working-directory: test

    - name: Generate code with AutoRest
      run: dotnet run --project ../src/ApiClientCodeGen.CLI/ApiClientCodeGen.CLI.csproj -- -v autorest ./OpenApi.yaml GeneratedCode ./GeneratedCode/AutoRest/Output.cs
      working-directory: test

    - name: Build .NET Core 2.1 AutoRest generated code
      run: dotnet build ./GeneratedCode/AutoRest/NetCore21.csproj
      working-directory: test

    - name: Build .NET Core 3.1 AutoRest generated code
      run: dotnet build ./GeneratedCode/AutoRest/NetCore31.csproj
      working-directory: test

    - name: Build .NET 5 AutoRest generated code
      run: dotnet build ./GeneratedCode/AutoRest/Net5.csproj
      working-directory: test

    - name: Generate code with NSwag
      run: dotnet run --project ../src/ApiClientCodeGen.CLI/ApiClientCodeGen.CLI.csproj -- -v nswag ./OpenApi.yaml GeneratedCode ./GeneratedCode/NSwag/Output.cs
      working-directory: test

    - name: Build .NET Core 2.1 NSwag generated code
      run: dotnet build ./GeneratedCode/NSwag/NetCore21.csproj
      working-directory: test

    - name: Build .NET Core 3.1 NSwag generated code
      run: dotnet build ./GeneratedCode/NSwag/NetCore31.csproj
      working-directory: test

    - name: Build .NET 5 NSwag generated code
      run: dotnet build ./GeneratedCode/NSwag/Net5.csproj
      working-directory: test

    - name: Generate code with Swagger Codegen CLI
      run: dotnet run --project ../src/ApiClientCodeGen.CLI/ApiClientCodeGen.CLI.csproj -- -v nswag ./OpenApi.yaml GeneratedCode ./GeneratedCode/SwaggerCodegen/Output.cs
      working-directory: test

    - name: Build .NET Core 2.1 Swagger Codegen CLI generated code
      run: dotnet build ./GeneratedCode/SwaggerCodegen/NetCore21.csproj
      working-directory: test

    - name: Build .NET Core 3.1 Swagger Codegen CLI generated code
      run: dotnet build ./GeneratedCode/SwaggerCodegen/NetCore31.csproj
      working-directory: test

    - name: Build .NET 5 Swagger Codegen CLI generated code
      run: dotnet build ./GeneratedCode/SwaggerCodegen/Net5.csproj
      working-directory: test

    - name: Generate code with OpenAPI Generator
      run: dotnet run --project ../src/ApiClientCodeGen.CLI/ApiClientCodeGen.CLI.csproj -- -v nswag ./OpenApi.yaml GeneratedCode ./GeneratedCode/OpenApiGenerator/Output.cs
      working-directory: test

    - name: Build .NET Core 2.1 OpenAPI Generator generated code
      run: dotnet build ./GeneratedCode/OpenApiGenerator/NetCore21.csproj
      working-directory: test

    - name: Build .NET Core 3.1 OpenAPI Generator generated code
      run: dotnet build ./GeneratedCode/OpenApiGenerator/NetCore31.csproj
      working-directory: test

    - name: Build .NET 5 OpenAPI Generator generated code
      run: dotnet build ./GeneratedCode/OpenApiGenerator/Net5.csproj
      working-directory: test

  test-petstore-v3-json:

    name: Swagger Petstore v3 (JSON)
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core 2.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1
    
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1
    
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0

    - name: Download Swagger Petstore v3 OpenAPI Spec
      run: Invoke-WebRequest -Uri https://petstore3.swagger.io/api/v3/openapi.json -OutFile OpenApi.json
      working-directory: test

    - name: Generate code with NSwag
      run: dotnet run --project ../src/ApiClientCodeGen.CLI/ApiClientCodeGen.CLI.csproj -- -v nswag ./OpenApi.json GeneratedCode ./GeneratedCode/NSwag/Output.cs
      working-directory: test

    - name: Build .NET Core 2.1 NSwag generated code
      run: dotnet build ./GeneratedCode/NSwag/NetCore21.csproj
      working-directory: test

    - name: Build .NET Core 3.1 NSwag generated code
      run: dotnet build ./GeneratedCode/NSwag/NetCore31.csproj
      working-directory: test

    - name: Build .NET 5 NSwag generated code
      run: dotnet build ./GeneratedCode/NSwag/Net5.csproj
      working-directory: test

    - name: Generate code with Swagger Codegen CLI
      run: dotnet run --project ../src/ApiClientCodeGen.CLI/ApiClientCodeGen.CLI.csproj -- -v nswag ./OpenApi.json GeneratedCode ./GeneratedCode/SwaggerCodegen/Output.cs
      working-directory: test

    - name: Build .NET Core 2.1 Swagger Codegen CLI generated code
      run: dotnet build ./GeneratedCode/SwaggerCodegen/NetCore21.csproj
      working-directory: test

    - name: Build .NET Core 3.1 Swagger Codegen CLI generated code
      run: dotnet build ./GeneratedCode/SwaggerCodegen/NetCore31.csproj
      working-directory: test

    - name: Build .NET 5 Swagger Codegen CLI generated code
      run: dotnet build ./GeneratedCode/SwaggerCodegen/Net5.csproj
      working-directory: test

    - name: Generate code with OpenAPI Generator
      run: dotnet run --project ../src/ApiClientCodeGen.CLI/ApiClientCodeGen.CLI.csproj -- -v nswag ./OpenApi.json GeneratedCode ./GeneratedCode/OpenApiGenerator/Output.cs
      working-directory: test

    - name: Build .NET Core 2.1 OpenAPI Generator generated code
      run: dotnet build ./GeneratedCode/OpenApiGenerator/NetCore21.csproj
      working-directory: test

    - name: Build .NET Core 3.1 OpenAPI Generator generated code
      run: dotnet build ./GeneratedCode/OpenApiGenerator/NetCore31.csproj
      working-directory: test

    - name: Build .NET 5 OpenAPI Generator generated code
      run: dotnet build ./GeneratedCode/OpenApiGenerator/Net5.csproj
      working-directory: test

  test-petstore-v3-yaml:

    name: Swagger Petstore v3 (YAML)
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core 2.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1
    
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1
    
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0

    - name: Download Swagger Petstore v3 OpenAPI Spec
      run: Invoke-WebRequest -Uri https://petstore3.swagger.io/api/v3/openapi.yaml -OutFile OpenApi.yaml
      working-directory: test

    - name: Generate code with NSwag
      run: dotnet run --project ../src/ApiClientCodeGen.CLI/ApiClientCodeGen.CLI.csproj -- -v nswag ./OpenApi.yaml GeneratedCode ./GeneratedCode/NSwag/Output.cs
      working-directory: test

    - name: Build .NET Core 2.1 NSwag generated code
      run: dotnet build ./GeneratedCode/NSwag/NetCore21.csproj
      working-directory: test

    - name: Build .NET Core 3.1 NSwag generated code
      run: dotnet build ./GeneratedCode/NSwag/NetCore31.csproj
      working-directory: test

    - name: Build .NET 5 NSwag generated code
      run: dotnet build ./GeneratedCode/NSwag/Net5.csproj
      working-directory: test

    - name: Generate code with Swagger Codegen CLI
      run: dotnet run --project ../src/ApiClientCodeGen.CLI/ApiClientCodeGen.CLI.csproj -- -v nswag ./OpenApi.yaml GeneratedCode ./GeneratedCode/SwaggerCodegen/Output.cs
      working-directory: test

    - name: Build .NET Core 2.1 Swagger Codegen CLI generated code
      run: dotnet build ./GeneratedCode/SwaggerCodegen/NetCore21.csproj
      working-directory: test

    - name: Build .NET Core 3.1 Swagger Codegen CLI generated code
      run: dotnet build ./GeneratedCode/SwaggerCodegen/NetCore31.csproj
      working-directory: test

    - name: Build .NET 5 Swagger Codegen CLI generated code
      run: dotnet build ./GeneratedCode/SwaggerCodegen/Net5.csproj
      working-directory: test

    - name: Generate code with OpenAPI Generator
      run: dotnet run --project ../src/ApiClientCodeGen.CLI/ApiClientCodeGen.CLI.csproj -- -v nswag ./OpenApi.yaml GeneratedCode ./GeneratedCode/OpenApiGenerator/Output.cs
      working-directory: test

    - name: Build .NET Core 2.1 OpenAPI Generator generated code
      run: dotnet build ./GeneratedCode/OpenApiGenerator/NetCore21.csproj
      working-directory: test

    - name: Build .NET Core 3.1 OpenAPI Generator generated code
      run: dotnet build ./GeneratedCode/OpenApiGenerator/NetCore31.csproj
      working-directory: test

    - name: Build .NET 5 OpenAPI Generator generated code
      run: dotnet build ./GeneratedCode/OpenApiGenerator/Net5.csproj
      working-directory: test
