name: Smoke Tests

on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'build/**'
      - 'images/**'
      - 'README.md'
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron:  '0 8 * * *'

jobs:

  test-petstore-v2-json:

    name: Swagger Petstore v2 (JSON)
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.607

    - name: Download Swagger Petstore v2 OpenAPI Spec
      run: Invoke-WebRequest -Uri https://petstore.swagger.io/v2/swagger.json -OutFile OpenApi.json
      working-directory: test

    - name: Generate code with AutoRest
      run: dotnet run --project ../src/ApiClientCodeGen.CLI/ApiClientCodeGen.CLI.csproj --framework netcoreapp2.1 -- -v autorest ./OpenApi.json GeneratedCode ./GeneratedCode/AutoRest/Output.cs
      working-directory: test

    - name: Build AutoRest generated code
      run: dotnet build ./GeneratedCode/AutoRest/Project.csproj
      working-directory: test

    - name: Generate code with NSwag
      run: dotnet run --project ../src/ApiClientCodeGen.CLI/ApiClientCodeGen.CLI.csproj --framework netcoreapp2.1 -- -v nswag ./OpenApi.json GeneratedCode ./GeneratedCode/NSwag/Output.cs
      working-directory: test

    - name: Build NSwag generated code
      run: dotnet build ./GeneratedCode/NSwag/Project.csproj
      working-directory: test

    - name: Generate code with Swagger Codegen CLI
      run: dotnet run --project ../src/ApiClientCodeGen.CLI/ApiClientCodeGen.CLI.csproj --framework netcoreapp2.1 -- -v nswag ./OpenApi.json GeneratedCode ./GeneratedCode/SwaggerCodegen/Output.cs
      working-directory: test

    - name: Build Swagger Codegen CLI generated code
      run: dotnet build ./GeneratedCode/SwaggerCodegen/Project.csproj
      working-directory: test

    - name: Generate code with OpenAPI Generator
      run: dotnet run --project ../src/ApiClientCodeGen.CLI/ApiClientCodeGen.CLI.csproj --framework netcoreapp2.1 -- -v nswag ./OpenApi.json GeneratedCode ./GeneratedCode/OpenApiGenerator/Output.cs
      working-directory: test

    - name: Build OpenAPI Generator generated code
      run: dotnet build ./GeneratedCode/OpenApiGenerator/Project.csproj
      working-directory: test

  test-petstore-v2-yaml:

    name: Swagger Petstore v2 (YAML)
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.607

    - name: Download Swagger Petstore v2 OpenAPI Spec
      run: Invoke-WebRequest -Uri https://petstore.swagger.io/v2/swagger.yaml -OutFile OpenApi.yaml
      working-directory: test

    - name: Generate code with AutoRest
      run: dotnet run --project ../src/ApiClientCodeGen.CLI/ApiClientCodeGen.CLI.csproj --framework netcoreapp2.1 -- -v autorest ./OpenApi.yaml GeneratedCode ./GeneratedCode/AutoRest/Output.cs
      working-directory: test

    - name: Build AutoRest generated code
      run: dotnet build ./GeneratedCode/AutoRest/Project.csproj
      working-directory: test

    - name: Generate code with NSwag
      run: dotnet run --project ../src/ApiClientCodeGen.CLI/ApiClientCodeGen.CLI.csproj --framework netcoreapp2.1 -- -v nswag ./OpenApi.yaml GeneratedCode ./GeneratedCode/NSwag/Output.cs
      working-directory: test

    - name: Build NSwag generated code
      run: dotnet build ./GeneratedCode/NSwag/Project.csproj
      working-directory: test

    - name: Generate code with Swagger Codegen CLI
      run: dotnet run --project ../src/ApiClientCodeGen.CLI/ApiClientCodeGen.CLI.csproj --framework netcoreapp2.1 -- -v nswag ./OpenApi.yaml GeneratedCode ./GeneratedCode/SwaggerCodegen/Output.cs
      working-directory: test

    - name: Build Swagger Codegen CLI generated code
      run: dotnet build ./GeneratedCode/SwaggerCodegen/Project.csproj
      working-directory: test

    - name: Generate code with OpenAPI Generator
      run: dotnet run --project ../src/ApiClientCodeGen.CLI/ApiClientCodeGen.CLI.csproj --framework netcoreapp2.1 -- -v nswag ./OpenApi.yaml GeneratedCode ./GeneratedCode/OpenApiGenerator/Output.cs
      working-directory: test

    - name: Build OpenAPI Generator generated code
      run: dotnet build ./GeneratedCode/OpenApiGenerator/Project.csproj
      working-directory: test

  test-petstore-v3-json:

    name: Swagger Petstore v3 (JSON)
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.607

    - name: Download Swagger Petstore v3 OpenAPI Spec
      run: Invoke-WebRequest -Uri https://petstore3.swagger.io/api/v3/openapi.json -OutFile OpenApi.json
      working-directory: test

    - name: Generate code with NSwag
      run: dotnet run --project ../src/ApiClientCodeGen.CLI/ApiClientCodeGen.CLI.csproj --framework netcoreapp2.1 -- -v nswag ./OpenApi.json GeneratedCode ./GeneratedCode/NSwag/Output.cs
      working-directory: test

    - name: Build NSwag generated code
      run: dotnet build ./GeneratedCode/NSwag/Project.csproj
      working-directory: test

    - name: Generate code with Swagger Codegen CLI
      run: dotnet run --project ../src/ApiClientCodeGen.CLI/ApiClientCodeGen.CLI.csproj --framework netcoreapp2.1 -- -v nswag ./OpenApi.json GeneratedCode ./GeneratedCode/SwaggerCodegen/Output.cs
      working-directory: test

    - name: Build Swagger Codegen CLI generated code
      run: dotnet build ./GeneratedCode/SwaggerCodegen/Project.csproj
      working-directory: test

    - name: Generate code with OpenAPI Generator
      run: dotnet run --project ../src/ApiClientCodeGen.CLI/ApiClientCodeGen.CLI.csproj --framework netcoreapp2.1 -- -v nswag ./OpenApi.json GeneratedCode ./GeneratedCode/OpenApiGenerator/Output.cs
      working-directory: test

    - name: Build OpenAPI Generator generated code
      run: dotnet build ./GeneratedCode/OpenApiGenerator/Project.csproj
      working-directory: test

  test-petstore-v3-yaml:

    name: Swagger Petstore v3 (YAML)
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.607

    - name: Download Swagger Petstore v3 OpenAPI Spec
      run: Invoke-WebRequest -Uri https://petstore3.swagger.io/api/v3/openapi.yaml -OutFile OpenApi.yaml
      working-directory: test

    - name: Generate code with NSwag
      run: dotnet run --project ../src/ApiClientCodeGen.CLI/ApiClientCodeGen.CLI.csproj --framework netcoreapp2.1 -- -v nswag ./OpenApi.yaml GeneratedCode ./GeneratedCode/NSwag/Output.cs
      working-directory: test

    - name: Build NSwag generated code
      run: dotnet build ./GeneratedCode/NSwag/Project.csproj
      working-directory: test

    - name: Generate code with Swagger Codegen CLI
      run: dotnet run --project ../src/ApiClientCodeGen.CLI/ApiClientCodeGen.CLI.csproj --framework netcoreapp2.1 -- -v nswag ./OpenApi.yaml GeneratedCode ./GeneratedCode/SwaggerCodegen/Output.cs
      working-directory: test

    - name: Build Swagger Codegen CLI generated code
      run: dotnet build ./GeneratedCode/SwaggerCodegen/Project.csproj
      working-directory: test

    - name: Generate code with OpenAPI Generator
      run: dotnet run --project ../src/ApiClientCodeGen.CLI/ApiClientCodeGen.CLI.csproj --framework netcoreapp2.1 -- -v nswag ./OpenApi.yaml GeneratedCode ./GeneratedCode/OpenApiGenerator/Output.cs
      working-directory: test

    - name: Build OpenAPI Generator generated code
      run: dotnet build ./GeneratedCode/OpenApiGenerator/Project.csproj
      working-directory: test
