name: Smoke Tests

on:
  push:
    paths-ignore:
      - '.github/workflows/**'
      - '!.github/workflows/smoke-tests.yml'
      - 'docs/**'
      - 'build/**'
      - 'images/**'
      - 'README.md'
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron:  '0 8 * * *'

jobs:

  Petstore:

    name: Swagger Petstore
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.os == 'macos-11.0' }}
    strategy:
      fail-fast: true
      matrix:
        format: [ json, yaml ]
        version: [ v2, v3 ]
        os: [
          ubuntu-20.04,
          ubuntu-18.04,
          ubuntu-16.04,
          macos-11.0,
          macos-10.15,
          windows-2019,
          windows-2016
        ]

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core 2.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1
    
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1

    - name: Setup .NET 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Download Swagger Petstore V2 OpenAPI Spec
      run: curl -sSL https://petstore.swagger.io/v2/swagger.${{ matrix.format }} -o OpenApi.${{ matrix.format }}
      if: ${{ matrix.version == 'v2' }}
      working-directory: test

    - name: Download Swagger Petstore V3 OpenAPI Spec
      run: curl -sSL https://petstore3.swagger.io/api/v3/openapi.${{ matrix.format }} -o OpenApi.${{ matrix.format }}
      if: ${{ matrix.version == 'v3' }}
      working-directory: test

    - name: Generate code with NSwag
      run: dotnet run --project ../src/CLI/ApiClientCodeGen.CLI/ApiClientCodeGen.CLI.csproj -- -v nswag ./OpenApi.${{ matrix.format }} GeneratedCode ./GeneratedCode/NSwag/Output.cs --no-logging
      working-directory: test

    - name: Build .NET Core 2.1 NSwag generated code
      run: dotnet build ./GeneratedCode/NSwag/NetCore21/NetCore21.csproj
      working-directory: test

    - name: Build .NET Core 3.1 NSwag generated code
      run: dotnet build ./GeneratedCode/NSwag/NetCore31/NetCore31.csproj
      working-directory: test

    - name: Build .NET 5 NSwag generated code
      run: dotnet build ./GeneratedCode/NSwag/Net5/Net5.csproj
      working-directory: test

    - name: Build .NET 4.8 NSwag generated code
      run: dotnet build ./GeneratedCode/NSwag/Net48/Net48.csproj
      working-directory: test

    - name: Build .NET 4.7.2 NSwag generated code
      run: dotnet build ./GeneratedCode/NSwag/Net472/Net472.csproj
      working-directory: test

    - name: Build .NET 4.6.2 NSwag generated code
      run: dotnet build ./GeneratedCode/NSwag/Net462/Net462.csproj
      working-directory: test

    - name: Build .NET 4.5.2 NSwag generated code
      run: dotnet build ./GeneratedCode/NSwag/Net452/Net452.csproj
      working-directory: test

    - name: Build .NET Standard 2.0 NSwag generated code
      run: dotnet build ./GeneratedCode/NSwag/NetStandard20/NetStandard20.csproj
      working-directory: test

    - name: Generate code with Swagger Codegen CLI
      run: dotnet run --project ../src/CLI/ApiClientCodeGen.CLI/ApiClientCodeGen.CLI.csproj -- -v nswag ./OpenApi.${{ matrix.format }} GeneratedCode ./GeneratedCode/SwaggerCodegen/Output.cs --no-logging
      working-directory: test

    - name: Build .NET Core 2.1 Swagger Codegen CLI generated code
      run: dotnet build ./GeneratedCode/SwaggerCodegen/NetCore21/NetCore21.csproj
      working-directory: test

    - name: Build .NET Core 3.1 Swagger Codegen CLI generated code
      run: dotnet build ./GeneratedCode/SwaggerCodegen/NetCore31/NetCore31.csproj
      working-directory: test

    - name: Build .NET 5 Swagger Codegen CLI generated code
      run: dotnet build ./GeneratedCode/SwaggerCodegen/Net5/Net5.csproj
      working-directory: test

    - name: Build .NET 4.8 Swagger Codegen CLI generated code
      run: dotnet build ./GeneratedCode/SwaggerCodegen/Net48/Net48.csproj
      working-directory: test

    - name: Build .NET 4.7.2 Swagger Codegen CLI generated code
      run: dotnet build ./GeneratedCode/SwaggerCodegen/Net472/Net472.csproj
      working-directory: test

    - name: Build .NET 4.6.2 Swagger Codegen CLI generated code
      run: dotnet build ./GeneratedCode/SwaggerCodegen/Net462/Net462.csproj
      working-directory: test

    - name: Build .NET 4.5.2 Swagger Codegen CLI generated code
      run: dotnet build ./GeneratedCode/SwaggerCodegen/Net452/Net452.csproj
      working-directory: test

    - name: Build .NET Standard 2.0 Swagger Codegen CLI generated code
      run: dotnet build ./GeneratedCode/SwaggerCodegen/NetStandard20/NetStandard20.csproj
      working-directory: test

    - name: Build .NET Standard 2.0 Swagger Codegen CLI generated code
      run: dotnet build ./GeneratedCode/SwaggerCodegen/NetStandard20/NetStandard20.csproj
      working-directory: test

    - name: Generate code with OpenAPI Generator
      run: dotnet run --project ../src/CLI/ApiClientCodeGen.CLI/ApiClientCodeGen.CLI.csproj -- -v nswag ./OpenApi.${{ matrix.format }} GeneratedCode ./GeneratedCode/OpenApiGenerator/Output.cs --no-logging
      working-directory: test

    - name: Build .NET Core 2.1 OpenAPI Generator generated code
      run: dotnet build ./GeneratedCode/OpenApiGenerator/NetCore21/NetCore21.csproj
      working-directory: test

    - name: Build .NET Core 3.1 OpenAPI Generator generated code
      run: dotnet build ./GeneratedCode/OpenApiGenerator/NetCore31/NetCore31.csproj
      working-directory: test

    - name: Build .NET 5 OpenAPI Generator generated code
      run: dotnet build ./GeneratedCode/OpenApiGenerator/Net5/Net5.csproj
      working-directory: test

    - name: Build .NET 4.8 OpenAPI Generator generated code
      run: dotnet build ./GeneratedCode/OpenApiGenerator/Net48/Net48.csproj
      working-directory: test

    - name: Build .NET 4.7.2 OpenAPI Generator generated code
      run: dotnet build ./GeneratedCode/OpenApiGenerator/Net472/Net472.csproj
      working-directory: test

    - name: Build .NET 4.6.2 OpenAPI Generator generated code
      run: dotnet build ./GeneratedCode/OpenApiGenerator/Net462/Net462.csproj
      working-directory: test

    - name: Build .NET 4.5.2 OpenAPI Generator generated code
      run: dotnet build ./GeneratedCode/OpenApiGenerator/Net452/Net452.csproj
      working-directory: test

    - name: Build .NET Standard 2.0 OpenAPI Generator generated code
      run: dotnet build ./GeneratedCode/OpenApiGenerator/NetStandard20/NetStandard20.csproj
      working-directory: test

  Petstore-AutoRest:

    name: Swagger Petstore (AutoRest)
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.os == 'macos-11.0' }}
    strategy:
      fail-fast: false
      matrix:
        node: [10, 12, 14, 15]
        format: [ json, yaml ]
        version: [ v2, v3 ]
        os: [
          ubuntu-20.04,
          ubuntu-18.04,
          ubuntu-16.04,
          macos-11.0,
          macos-10.15,
          windows-2019,
          windows-2016
        ]

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    
    - name: Setup .NET Core 2.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.0
    
    - name: Setup .NET Core 2.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1
    
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1

    - name: Download Swagger Petstore V2 OpenAPI Spec
      run: curl -sSL https://petstore.swagger.io/v2/swagger.${{ matrix.format }} -o OpenApi.${{ matrix.format }}
      if: ${{ matrix.version == 'v2' }}
      working-directory: test

    - name: Download Swagger Petstore V3 OpenAPI Spec
      run: curl -sSL https://petstore3.swagger.io/api/v3/openapi.${{ matrix.format }} -o OpenApi.${{ matrix.format }}
      if: ${{ matrix.version == 'v3' }}
      working-directory: test

    - name: Generate code with AutoRest
      run: dotnet run --project ../src/CLI/ApiClientCodeGen.CLI/ApiClientCodeGen.CLI.csproj -- -v autorest ./OpenApi.${{ matrix.format }} GeneratedCode ./GeneratedCode/AutoRest/Output.cs --no-logging
      working-directory: test
      continue-on-error: ${{ contains(matrix.os, 'ubuntu') }}

    - name: Build .NET Core 2.1 AutoRest generated code
      run: dotnet build ./GeneratedCode/AutoRest/NetCore21/NetCore21.csproj
      working-directory: test

    - name: Build .NET Core 3.1 AutoRest generated code
      run: dotnet build ./GeneratedCode/AutoRest/NetCore31/NetCore31.csproj
      working-directory: test

    - name: Build .NET 5 AutoRest generated code
      run: dotnet build ./GeneratedCode/AutoRest/Net5/Net5.csproj
      working-directory: test

    - name: Build .NET 4.8 AutoRest generated code
      run: dotnet build ./GeneratedCode/AutoRest/Net48/Net48.csproj
      working-directory: test

    - name: Build .NET 4.7.2 AutoRest generated code
      run: dotnet build ./GeneratedCode/AutoRest/Net472/Net472.csproj
      working-directory: test

    - name: Build .NET 4.6.2 AutoRest generated code
      run: dotnet build ./GeneratedCode/AutoRest/Net462/Net462.csproj
      working-directory: test

    - name: Build .NET 4.5.2 AutoRest generated code
      run: dotnet build ./GeneratedCode/AutoRest/Net452/Net452.csproj
      working-directory: test

    - name: Build .NET Standard 2.0 AutoRest generated code
      run: dotnet build ./GeneratedCode/AutoRest/NetStandard20/NetStandard20.csproj
      working-directory: test