name: Smoke Tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron:  '0 8 * * *'

jobs:

  test-petstore-v2:

    name: Swagger Petstore v2
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.607

    - name: Download Swagger Petstore v2 OpenAPI Spec
      run: Invoke-WebRequest -Uri https://petstore.swagger.io/v2/swagger.json -OutFile Swagger.json
      working-directory: test

    - name: Generate code with AutoRest
      run: |
        dotnet run --project ../src/ApiClientCodeGen.CLI/ApiClientCodeGen.CLI.csproj -- -v autorest ./Swagger.json GeneratedCode ./GeneratedCode/AutoRest/Output.cs
        dotnet build ./GeneratedCode/AutoRest/Project.csproj
      working-directory: test

    - name: Generate code with NSwag
      run: |
        dotnet run --project ../src/ApiClientCodeGen.CLI/ApiClientCodeGen.CLI.csproj -- -v -v nswag ./Swagger.json GeneratedCode ./GeneratedCode/NSwag/Output.cs
        dotnet build ./GeneratedCode/NSwag/Project.csproj
      working-directory: test

    - name: Generate code with Swagger Codegen CLI
      run: |
        dotnet run --project ../src/ApiClientCodeGen.CLI/ApiClientCodeGen.CLI.csproj -- -v -v nswag ./Swagger.json GeneratedCode ./GeneratedCode/SwaggerCodegen/Output.cs
        dotnet build ./GeneratedCode/SwaggerCodegen/Project.csproj
      working-directory: test

    - name: Generate code with OpenAPI Generator
      run: |
        dotnet run --project ../src/ApiClientCodeGen.CLI/ApiClientCodeGen.CLI.csproj -- -v -v nswag ./Swagger.json GeneratedCode ./GeneratedCode/OpenApiGenerator/Output.cs
        dotnet build ./GeneratedCode/OpenApiGenerator/Project.csproj
      working-directory: test

  test-petstore-v3:

    name: Swagger Petstore v3
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.607

    - name: Download Swagger Petstore v3 OpenAPI Spec
      run: Invoke-WebRequest -Uri https://petstore3.swagger.io/api/v3/openapi.json -OutFile Swagger.json
      working-directory: test

    - name: Generate code with NSwag
      run: |
        dotnet run --project ../src/ApiClientCodeGen.CLI/ApiClientCodeGen.CLI.csproj -- -v nswag ./Swagger.json GeneratedCode ./GeneratedCode/NSwag/Output.cs
        dotnet build ./GeneratedCode/NSwag/Project.csproj
      working-directory: test

    - name: Generate code with Swagger Codegen CLI
      run: |
        dotnet run --project ../src/ApiClientCodeGen.CLI/ApiClientCodeGen.CLI.csproj -- -v nswag ./Swagger.json GeneratedCode ./GeneratedCode/SwaggerCodegen/Output.cs
        dotnet build ./GeneratedCode/SwaggerCodegen/Project.csproj
      working-directory: test

    - name: Generate code with OpenAPI Generator
      run: |
        dotnet run --project ../src/ApiClientCodeGen.CLI/ApiClientCodeGen.CLI.csproj -- -v nswag ./Swagger.json GeneratedCode ./GeneratedCode/OpenApiGenerator/Output.cs
        dotnet build ./GeneratedCode/OpenApiGenerator/Project.csproj
      working-directory: test
