name: Unit Tests

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**/*'
      - '!.github/workflows/unit-tests.yml'
      - '!src/**/*.csproj'
      - '!src/**/*.cs'
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron:  '0 8 * * *'

jobs:

  rapicgen:

    name: CLI Tool
    runs-on: windows-2019
    timeout-minutes: 20

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: 14
    
    - name: Setup .NET Core 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1

    - name: Setup .NET 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.104'

    - name: Build with dotnet
      run: dotnet build Rapicgen.sln
      working-directory: src

    - name: Core test project
      run: dotnet test src/Core/ApiClientCodeGen.Core.Tests\ApiClientCodeGen.Core.Tests.csproj

    - name: Core Integration Test project
      run: dotnet test src/Core/ApiClientCodeGen.Core.IntegrationTests\ApiClientCodeGen.Core.IntegrationTests.csproj

  vsmac:

    name: VS Mac Extension
    runs-on: macos-10.15
    timeout-minutes: 20

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1

    - name: Build
      run: make release
      working-directory: src

    - name: Core Test project
      run: dotnet test src/Core/ApiClientCodeGen.Core.Tests/ApiClientCodeGen.Core.Tests.csproj -f netcoreapp3.1

    - name: Core Integration Test project
      run: dotnet test src/Core/ApiClientCodeGen.Core.IntegrationTests/ApiClientCodeGen.Core.IntegrationTests.csproj -f netcoreapp3.1

  vsix:

    name: VSIX Extension
    runs-on: windows-2019
    timeout-minutes: 20

    steps:
    - uses: actions/checkout@v2

    - name: Build VSIX
      run: powershell ./build.ps1 --target VSIX
      working-directory: src

    - name: Run Tests
      run: powershell ./build.ps1 --target Run-All-Tests
      working-directory: src
