name: Unit Tests

on:
  push:
    paths-ignore:
      - '.github/workflows/**'
      - '!.github/workflows/unit-tests.yml'
      - 'docs/**'
      - 'test/**'
      - 'build/**'
      - 'images/**'
      - 'README.md'
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron:  '0 8 * * *'

jobs:

  rapicgen:

    name: CLI Tool
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.607

    - name: Build with dotnet
      run: dotnet build Rapicgen.sln
      working-directory: src

    - name: Core test project
      run: dotnet test src/Core/ApiClientCodeGen.Core.Tests\ApiClientCodeGen.Core.Tests.csproj

    - name: Core Integration Test project
      run: dotnet test src/Core/ApiClientCodeGen.Core.IntegrationTests\ApiClientCodeGen.Core.IntegrationTests.csproj

  vsmac:

    name: VS Mac Extension

    strategy:
      matrix:
        os: [macos-11.0, macos-10.15]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.607

    - name: Build
      run: make release
      working-directory: src

    - name: Core Test project
      run: dotnet test src/Core/ApiClientCodeGen.Core.Tests/ApiClientCodeGen.Core.Tests.csproj -f netcoreapp2.1

    - name: Core Integration Test project
      run: dotnet test src/Core/ApiClientCodeGen.Core.IntegrationTests/ApiClientCodeGen.Core.IntegrationTests.csproj -f netcoreapp2.1

  vsix:

    name: VSIX Extension
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.607

    - name: Build VSIX
      run: powershell build.ps1 --target VSIX
      working-directory: src

    - name: Run Tests
      run: powershell build.ps1 --target Run-All-Tests
      working-directory: src
