name: Visual Studio Extension

on: [push]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2

    - name: Cake Build
      run: powershell ./build.ps1
      working-directory: src

    - name: Publish artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Artifacts
        path: |
          **/*.vsix
