name: VSIX Tests

on:
  workflow_dispatch:
  push:
    paths: 
    - '.github/workflows/vsix-tests.yml'
    branches: 
    - '*'
  schedule:
    - cron: '0 8 * * *'

jobs:

  VSIX2019:
    runs-on: windows-2019
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        node: [12, 14, 15, 16]
        format: [ json, yaml ]
        version: [ V2, V3 ]
    steps:
    - name: Download VSIX for VS 2019
      run: |
        $marketplace = 'https://marketplace.visualstudio.com/items?itemName=ChristianResmaHelle.ApiClientCodeGenerator'
        $path = ((Invoke-WebRequest -Uri $marketplace).Links | Where class -eq 'install-button-container').Href
        $downloadUri = "https://marketplace.visualstudio.com$path"
        Invoke-WebRequest $downloadUri -OutFile "vs2019.vsix"
    - name: Install VSIX
      run: Start-Process -FilePath 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\VSIXInstaller.exe' -ArgumentList '/q vs2019.vsix' -Wait

  VSIX2022:
    runs-on: windows-2022
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        node: [12, 14, 15, 16]
        format: [ json, yaml ]
        version: [ V2, V3 ]
    steps:
    - name: Download VSIX for VS 2022
      run: |
        $marketplace = 'https://marketplace.visualstudio.com/items?itemName=ChristianResmaHelle.ApiClientCodeGenerator2022'
        $path = ((Invoke-WebRequest -Uri $marketplace).Links | Where class -eq 'install-button-container').Href
        $downloadUri = "https://marketplace.visualstudio.com$path"
        Invoke-WebRequest $downloadUri -OutFile "vs2022.vsix"
    - name: Install VSIX
      run: Start-Process -FilePath 'C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\VSIXInstaller.exe' -ArgumentList '/q vs2019.vsix' -Wait