name: VSIX

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/workflows/**'
      - '!.github/workflows/vsix.yml'
      - 'docs/**'
      - 'test/**'
      - 'build/**'
      - 'images/**'
      - 'README.md'
      - 'src/CLI/ApiClientCodeGen.CLI*/**'
      - 'src/VSMac/ApiClientCodeGen.VSMac*/**'
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron:  '0 8 * * *'

env:
  VSIX_VERSION: 1.4.${{ github.run_number }}

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2

    - run: npm install -g autorest
    - run: npm install -g nswag

    - name: Update VSIX Version
      run: |
        ((Get-Content -path VSIX/ApiClientCodeGen.VSIX/source.extension.vsixmanifest -Raw) -replace 'Version="1.0.0"', "Version=""$VSIX_VERSION""") | Set-Content -Path VSIX/ApiClientCodeGen.VSIX/source.extension.vsixmanifest
        ((Get-Content -path VSIX/ApiClientCodeGen.VSIX.Dev17/source.extension.vsixmanifest -Raw) -replace 'Version="1.0.0"', "Version=""$VSIX_VERSION""") | Set-Content -Path VSIX/ApiClientCodeGen.VSIX.Dev17/source.extension.vsixmanifest
      working-directory: src
      shell: pwsh

    - name: Cake Build
      run: powershell ./build.ps1 --target VSIX
      working-directory: src

    - name: Move build output
      run: |
        mv VSIX/ApiClientCodeGen.VSIX/bin/Release/ApiClientCodeGenerator.vsix ApiClientCodeGenerator-$VSIX_VERSION.vsix
        mv VSIX/ApiClientCodeGen.VSIX.Dev17/bin/Release/ApiClientCodeGenerator.vsix ApiClientCodeGenerator-VS2022-$VSIX_VERSION.vsix
      working-directory: src

    - name: Publish artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Artifacts
        path: |
          src/*.vsix
          docs/Marketplace*.md
