name: VSIX

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/workflows/**'
      - '!.github/workflows/vsix.yml'
      - 'docs/**'
      - 'test/**'
      - 'build/**'
      - 'images/**'
      - 'README.md'
      - 'src/CLI/ApiClientCodeGen.CLI*/**'
      - 'src/VSMac/ApiClientCodeGen.VSMac*/**'
      - 'src/*.json'
      - 'src/*.ps1'
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron:  '0 8 * * *'

env:
  VERSION: 1.5.0.${{ github.run_number }}

jobs:
  build:

    runs-on: windows-2019
    timeout-minutes: 20

    steps:
    - uses: actions/checkout@v2

    - name: Update Version
      run: |
        ((Get-Content -Path Core/ApiClientCodeGen.Core/ApiClientCodeGen.Core.csproj -Raw) -Replace "1.0.0", "${{ env.VERSION }}") | Set-Content -Path Core/ApiClientCodeGen.Core/ApiClientCodeGen.Core.csproj
        ((Get-Content -Path VSIX/ApiClientCodeGen.VSIX/source.extension.vsixmanifest -Raw) -Replace "1.0.0", "${{ env.VERSION }}") | Set-Content -Path VSIX/ApiClientCodeGen.VSIX/source.extension.vsixmanifest
      working-directory: src
      shell: pwsh

    - name: Cake Build
      run: powershell ./build.ps1 --target VSIX
      working-directory: src

    - name: Move build output
      run: |
        mv src/VSIX/ApiClientCodeGen.VSIX/bin/Release/ApiClientCodeGenerator.vsix ApiClientCodeGenerator-${{ env.VERSION }}.vsix

    - name: Publish artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Artifacts
        path: |
          *.vsix
          docs/Marketplace*.md

    - name: Publish to Open VSIX Gallery
      if: github.ref == 'refs/heads/master'
      run: |
        (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex
        Vsix-PushArtifacts
        Vsix-PublishToGallery -path ApiClientCodeGenerator-${{ env.VERSION }}.vsix -readmeUrl https://raw.githubusercontent.com/christianhelle/apiclientcodegen/master/docs/Marketplace.md
      shell: pwsh
