name: VSIX

on:
  workflow_dispatch:
  push:
  pull_request:
    branches:
      - '*'
  schedule:
    - cron:  '0 8 * * *'

env:
  VERSION: 1.5.0.${{ github.run_number }}

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Update Version
      run: |
        ((Get-Content -Path Core/ApiClientCodeGen.Core/ApiClientCodeGen.Core.csproj -Raw) -Replace "1.0.0", "${{ env.VERSION }}") | Set-Content -Path Core/ApiClientCodeGen.Core/ApiClientCodeGen.Core.csproj
        ((Get-Content -Path VSIX/ApiClientCodeGen.VSIX.Dev15/source.extension.vsixmanifest -Raw) -Replace "1.0.0", "${{ env.VERSION }}") | Set-Content -Path VSIX/ApiClientCodeGen.VSIX.Dev15/source.extension.vsixmanifest
      working-directory: src
      shell: pwsh

    - name: Restore
      run: dotnet restore VSIX.sln
      working-directory: src

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1

    - name: Build
      run: msbuild VSIX.sln /property:Configuration=Release /t:Rebuild
      working-directory: src

    - name: Move build output
      run: |
        mv src/VSIX/ApiClientCodeGen.VSIX.Dev15/bin/Release/ApiClientCodeGenerator.vsix ApiClientCodeGenerator-Legacy-${{ env.VERSION }}.vsix

    - name: Publish artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Artifacts
        path: |
          *.vsix
          docs/Marketplace*.md

    - name: Publish to Open VSIX Gallery
      if: github.ref == 'refs/heads/master'
      run: |
        (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex
        Vsix-PushArtifacts
        Vsix-PublishToGallery -path ApiClientCodeGenerator-Legacy-${{ env.VERSION }}.vsix -readmeUrl https://raw.githubusercontent.com/christianhelle/apiclientcodegen/master/docs/Marketplace2017.md
      shell: pwsh
      continue-on-error: true
