name: VSIX

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron:  '0 8 * * *'

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2

    - run: npm install -g autorest
    - run: npm install -g nswag

    - name: Cake Build
      run: powershell ./build.ps1
      working-directory: src

    - name: Move build output
      run: mv ApiClientCodeGen.VSIX/bin/Release/ApiClientCodeGenerator.vsix ApiClientCodeGenerator-1.0.${{ github.run_number }}.vsix
      working-directory: src

    - name: Publish artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Artifacts
        path: |
          src/*.vsix
