name: VS Mac

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron:  '0 8 * * *'

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Update Extension Version Info
      run: |
        sed -i -e 's/1.0/1.0.${{ github.run_number }}/g' ./AddinInfo.cs
        cat ./AddinInfo.cs
      working-directory: src/ApiClientCodeGen.VSMac/Properties

    - name: Build
      run: make package
      working-directory: src

    - name: Archive binaries
      run: zip -r VSMac-Binaries.zip .
      working-directory: src/ApiClientCodeGen.VSMac/bin/Release/net48/

    - name: Publish binaries
      uses: actions/upload-artifact@v2
      with:
        name: Binaries
        path: src/ApiClientCodeGen.VSMac/bin/Release/net48/VSMac-Binaries.zip

    - name: Create mpack file
      run: /Applications/Visual\ Studio.app/Contents/MacOS/vstool setup pack ApiClientCodeGen.VSMac.dll -d:"../../../../../src"
      working-directory: src/ApiClientCodeGen.VSMac/bin/Release/net48/

    - name: Rename build output
      run: mv *.mpack ApiClientCodeGenerator-1.0.${{ github.run_number }}.mpack
      working-directory: src

    - name: Create MonoDevelop Extension repository files
      run: make publish
      working-directory: src

    - name: Publish artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Extension
        path: |
          src/*.mpack
          src/*.mrep
          src/index.html
