name: VS Mac

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**/*'
      - '!.github/workflows/vsmac.yml'
      - '!src/VSMac/**/*'
      - '!src/Core/**/*'
    branches:
      - '*'
  # pull_request:
  #   branches:
  #     - '*'
  # schedule:
  #   - cron:  '0 8 * * *'

jobs:
  build:

    strategy:
      matrix:
        os: [macos-latest]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2

    - name: Update Extension Version Info
      run: |
        sed -i -e 's/1.0/1.0.${{ github.run_number }}/g' ./AddinInfo.cs
        cat ./AddinInfo.cs
      working-directory: src/VSMac/ApiClientCodeGen.VSMac/Properties

    - name: Setup .NET versions
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore
      run: dotnet restore ./Mac.sln
      working-directory: src

    - name: Build
      run: dotnet build -c Release ApiClientCodeGen.VSMac.csproj
      working-directory: src/VSMac/ApiClientCodeGen.VSMac

    - name: Package
      run: /Applications/Visual\ Studio.app/Contents/MacOS/vstool setup pack $PWD/VSMac/ApiClientCodeGen.VSMac/bin/Release/net6.0/ApiClientCodeGen.VSMac.dll -d:$PWD
      working-directory: src

    - name: Publish
      run: /Applications/Visual\ Studio.app/Contents/MacOS/vstool setup rep-build $PWD
      working-directory: src

    - name: Archive binaries
      run: zip -r VSMac-Binaries.zip .
      working-directory: src/VSMac/ApiClientCodeGen.VSMac/bin/Release/net472/

    - name: Publish binaries
      uses: actions/upload-artifact@v2
      with:
        name: Binaries
        path: src/VSMac/ApiClientCodeGen.VSMac/bin/Release/net472/VSMac-Binaries.zip

    - name: Create mpack file
      run: make package
      working-directory: src

    - name: Rename build output
      run: mv *.mpack ApiClientCodeGenerator-1.0.${{ github.run_number }}.mpack
      working-directory: src

    - name: Create MonoDevelop Extension repository files
      run: make publish
      working-directory: src

    - name: Publish artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Extension
        path: |
          src/*.mpack
          src/*.mrep
          src/index.html
          docs/VisualStudioForMac.md
