name: VS Mac

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '.github/workflows/**'
      - 'docs/**'
      - 'test/**'
      - 'build/**'
      - 'images/**'
      - 'README.md'
      - 'src/CLI/ApiClientCodeGen.CLI*/**'
      - 'src/VSIX/ApiClientCodeGen.VSIX*/**'
      - 'src/VSIX/ApiClientCodeGen.Tests/**'
      - 'src/VSIX/ApiClientCodeGen.IntegrationTests/**'
      - 'src/*.json'
      - 'src/*.ps1'
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron:  '0 8 * * *'

jobs:
  build:

    strategy:
      matrix:
        #os: [macos-11.0, macos-10.15] TODO: Fix failing builds on Visual Studio 2022 for Mac
        os: [macos-10.15]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 20

    steps:
    - uses: actions/checkout@v2

    - name: Update Extension Version Info
      run: |
        sed -i -e 's/1.0/1.0.${{ github.run_number }}/g' ./AddinInfo.cs
        cat ./AddinInfo.cs
      working-directory: src/VSMac/ApiClientCodeGen.VSMac/Properties

    - name: Build
      run: make release
      working-directory: src

    - name: Archive binaries
      run: zip -r VSMac-Binaries.zip .
      working-directory: src/VSMac/ApiClientCodeGen.VSMac/bin/Release/net472/

    - name: Publish binaries
      uses: actions/upload-artifact@v2
      with:
        name: Binaries
        path: src/VSMac/ApiClientCodeGen.VSMac/bin/Release/net472/VSMac-Binaries.zip

    - name: Create mpack file
      run: make package
      working-directory: src

    - name: Rename build output
      run: mv *.mpack ApiClientCodeGenerator-1.0.${{ github.run_number }}.mpack
      working-directory: src

    - name: Create MonoDevelop Extension repository files
      run: make publish
      working-directory: src

    - name: Publish artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Extension
        path: |
          src/*.mpack
          src/*.mrep
          src/index.html
          docs/VisualStudioForMac.md
