name: VS Mac

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Restore Packages
      run: nuget restore Mac.sln
      working-directory: src

    - name: Build
      run: msbuild /p:Configuration="Release" /t:"Rebuild" Mac.sln
      working-directory: src
