name: VS Mac

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**/*'
      - '!.github/workflows/vsmac.yml'
      - '!src/VSMac/**/*'
      - '!src/Core/**/*'
      - '!src/Makefile'
      - '!src/global.json'
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron:  '0 8 * * *'

env:
  VERSION: 1.7.${{ github.run_number }}

jobs:
  build:

    strategy:
      matrix:
        os: [macos-latest]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 20

    steps:
    - uses: actions/checkout@v2

    - name: Update Extension Version Info
      run: |
        sed -i -e 's/1.0/${{ env.VERSION }}/g' ./AddinInfo.cs
        cat ./AddinInfo.cs
      working-directory: src/VSMac/ApiClientCodeGen.VSMac/Properties

    - name: Setup .NET versions
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        global-json-file: src/global.json

    - name: Build
      run: make
      working-directory: src

    - name: Archive binaries
      run: zip -r VSMac-Binaries.zip .
      working-directory: src/VSMac/ApiClientCodeGen.VSMac/bin/Release/

    - name: Publish binaries
      uses: actions/upload-artifact@v2
      with:
        name: Binaries
        path: src/VSMac/ApiClientCodeGen.VSMac/bin/Release/VSMac-Binaries.zip

    - name: Rename build output
      run: mv *.mpack ApiClientCodeGenerator-${{ env.VERSION }}.mpack
      working-directory: src

    - name: Publish artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Extension
        path: |
          src/*.mpack
          src/*.mrep
          src/index.html
          docs/VisualStudioForMac.md
